# version: "3.9"
# services:
#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#       - 6379:6379
#   node-backend:
#     build: 
#       context: ./
#       dockerfile: Dockerfile
#     container_name: mern-gs
#     ports:
#       - 3000:3000
#     depends_on:
#       - redis
#     environment:
#       - REDIS_HOST=localhost
#       - REDIS_PORT=6379
  # react-frontend:
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: client
  #   ports:
  #     - 5173:5173
  #   depends_on:
  #     - node-backend
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  version: "3.9"
  services:
    backend:
      build: .
      container_name: node-backend
      ports:
        - "3000:3000"
      volumes:
        - ./:/app
        - /app/node_modules
      environment:
        - REDIS_URL=redis://redis:6379
      depends_on:
        redis:
          condition: service_healthy

    redis:
      image: redis:6.2
      container_name: redis-server
      ports:
        - "6379:6379"
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

    frontend:
      build: ./client
      container_name: react-frontend
      ports:
        - "4000:4000"
      stdin_open: true
      tty: true
      command: npm run dev
      depends_on:
        - backend

